# Generated by Django 4.1.5 on 2023-01-10 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="datos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                (
                    "cedula",
                    models.CharField(
                        max_length=11,
                        validators=[django.core.validators.MinLengthValidator(11)],
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        max_length=10,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "grado_academico",
                    models.CharField(
                        choices=[
                            ("PRIMARIO", "Primario"),
                            ("SECUNDARIO", "Secundario"),
                            ("UNIVERSITARIO", "Universitario"),
                        ],
                        max_length=100,
                    ),
                ),
                ("ocupacion", models.CharField(max_length=100)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino")],
                        default="Masculino",
                        max_length=100,
                    ),
                ),
                (
                    "denominacion",
                    models.CharField(
                        choices=[
                            ("CATOLICA", "Católica"),
                            ("ADVENTISTA", "Adventista"),
                            ("EVANGELICA", "Evangélica"),
                            ("TESTIGO DE JEHOVA", "Testigo de Jehova"),
                            ("MORMONA", "Mormona"),
                            ("UNIVERSAL", "Universal"),
                            ("CRISTIANA", "Cristiana"),
                            ("OTRA", "Otra"),
                        ],
                        max_length=100,
                    ),
                ),
                ("fecha_nacimiento", models.DateField()),
                (
                    "pais",
                    models.CharField(
                        choices=[
                            ("ARGENTINA", "Argentina"),
                            ("BOLIVIA", "Bolivia"),
                            ("BRASIL", "Brasil"),
                            ("COLOMBIA", "Colombia"),
                            ("COSTA RICA", "Costa Rica"),
                            ("CUBA", "Cuba"),
                            ("CHILE", "Chile"),
                            ("ECUADOR", "Ecuador"),
                            ("EL SALVADOR", "El Salvador"),
                            ("GUATEMALA", "Guatemala"),
                        ],
                        default="Brasil",
                        max_length=100,
                    ),
                ),
                ("provincia", models.CharField(max_length=100)),
                ("sector", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
